import { CATEGORY_TYPE } from "@/consts/category-type";
import { DIMENSION_TYPE } from "@/consts/dimension-type";
import { PROJECT_NAME } from "@/consts/project-name";
import { IPhoto } from "@/types/photo";
import img33 from "../../public/cars/car (33).jpg";

export const IMAGES: IPhoto[] = [
  // {
  //   src: require("../../public/cars/car (1).jpg"),
  //   id: 1,
  //   category: CATEGORY_TYPE.porsche,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 2.75,
  // },
  // {
  //   src: require("../../public/cars/car (2).jpg"),
  //   id: 2,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.white,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 5.5,
  // },
  // {
  //   src: require("../../public/cars/car (3).jpg"),
  //   id: 3,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 8.25,
  // },
  // {
  //   src: require("../../public/cars/car (4).jpg"),
  //   id: 4,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 11,
  // },
  // {
  //   src: require("../../public/cars/car (5).jpg"),
  //   id: 5,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 13.75,
  // },
  // {
  //   src: require("../../public/cars/car (6).jpg"),
  //   id: 6,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 16.5,
  // },
  // {
  //   src: require("../../public/cars/car (7).jpg"),
  //   id: 7,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 19.25,
  // },
  // {
  //   src: require("../../public/cars/car (8).jpg"),
  //   id: 8,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 22,
  // },
  // {
  //   src: require("../../public/cars/car (9).jpg"),
  //   id: 9,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 24.75,
  // },
  // {
  //   src: require("../../public/cars/car (10).jpg"),
  //   id: 10,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 27.5,
  // },
  // {
  //   src: require("../../public/cars/car (11).jpg"),
  //   id: 11,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 30.25,
  // },
  // {
  //   src: require("../../public/cars/car (12).jpg"),
  //   id: 12,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 33,
  // },
  // {
  //   src: require("../../public/cars/car (13).jpg"),
  //   id: 13,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 35.75,
  // },
  // {
  //   src: require("../../public/cars/car (14).jpg"),
  //   id: 14,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 38.5,
  // },
  // {
  //   src: require("../../public/cars/car (15).jpg"),
  //   id: 15,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 41.25,
  // },
  // {
  //   src: require("../../public/cars/car (16).jpg"),
  //   id: 16,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 44,
  // },
  // {
  //   src: require("../../public/cars/car (17).jpg"),
  //   id: 17,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 46.75,
  // },
  // {
  //   src: require("../../public/cars/car (18).jpg"),
  //   id: 18,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 49.5,
  // },
  // {
  //   src: require("../../public/cars/car (19).jpg"),
  //   id: 19,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 52.25,
  // },
  // {
  //   src: require("../../public/cars/car (20).jpg"),
  //   id: 20,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 55,
  // },
  // {
  //   src: require("../../public/cars/car (21).jpg"),
  //   id: 21,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 57.75,
  // },
  // {
  //   src: require("../../public/cars/car (22).jpg"),
  //   id: 22,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 60.5,
  // },
  // {
  //   src: require("../../public/cars/car (23).jpg"),
  //   id: 23,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 63.25,
  // },
  // {
  //   src: require("../../public/cars/car (24).jpg"),
  //   id: 24,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 66,
  // },
  // {
  //   src: require("../../public/cars/car (25).jpg"),
  //   id: 25,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 68.75,
  // },
  // {
  //   src: require("../../public/cars/car (26).jpg"),
  //   id: 26,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 71.5,
  // },
  // {
  //   src: require("../../public/cars/car (27).jpg"),
  //   id: 27,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 74.25,
  // },
  // {
  //   src: require("../../public/cars/car (28).jpg"),
  //   id: 28,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 77,
  // },
  // {
  //   src: require("../../public/cars/car (29).jpg"),
  //   id: 29,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 79.75,
  // },
  // {
  //   src: require("../../public/cars/car (30).jpg"),
  //   id: 30,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 82.5,
  // },
  // {
  //   src: require("../../public/cars/car (31).jpg"),
  //   id: 31,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 85.25,
  // },
  // {
  //   src: require("../../public/cars/car (32).jpg"),
  //   id: 32,
  //   category: CATEGORY_TYPE.ferrari,
  //   name: "ferrari1",
  //   project: PROJECT_NAME.red,
  //   dimension: DIMENSION_TYPE["7*5"],
  //   price: 88,
  // },
  {
    src: img33,
    id: 33,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: DIMENSION_TYPE["7*5"],
    price: 90.75,
  },
];
