import { CATEGORY_TYPE } from "@/consts/category-type";
import { DIMENSION_TYPE } from "@/consts/dimension-type";
import { PROJECT_NAME } from "@/consts/project-name";
import { IPhoto } from "@/types/photo";
import img1 from "../../public/cars/car (1).jpg";
import img2 from "../../public/cars/car (2).jpg";
import img3 from "../../public/cars/car (3).jpg";
import img4 from "../../public/cars/car (4).jpg";
import img5 from "../../public/cars/car (5).jpg";
import img6 from "../../public/cars/car (6).jpg";
import img7 from "../../public/cars/car (7).jpg";
import img8 from "../../public/cars/car (8).jpg";
import img9 from "../../public/cars/car (9).jpg";
import img10 from "../../public/cars/car (10).jpg";
import img11 from "../../public/cars/car (11).jpg";
import img12 from "../../public/cars/car (12).jpg";
import img13 from "../../public/cars/car (13).jpg";
import img14 from "../../public/cars/car (14).jpg";
import img15 from "../../public/cars/car (15).jpg";
import img16 from "../../public/cars/car (16).jpg";
import img17 from "../../public/cars/car (17).jpg";
import img18 from "../../public/cars/car (18).jpg";
import img19 from "../../public/cars/car (19).jpg";
import img20 from "../../public/cars/car (20).jpg";
import img21 from "../../public/cars/car (21).jpg";
import img22 from "../../public/cars/car (22).jpg";
import img23 from "../../public/cars/car (23).jpg";
import img24 from "../../public/cars/car (24).jpg";
import img25 from "../../public/cars/car (25).jpg";
import img26 from "../../public/cars/car (26).jpg";
import img27 from "../../public/cars/car (27).jpg";
import img28 from "../../public/cars/car (28).jpg";
import img29 from "../../public/cars/car (29).jpg";
import img30 from "../../public/cars/car (30).jpg";
import img31 from "../../public/cars/car (31).jpg";
import img32 from "../../public/cars/car (32).jpg";
import img33 from "../../public/cars/car (33).jpg";

export const IMAGES: IPhoto[] = [
  {
    src: img1,
    purchaseLink: "",
    id: 1,
    category: CATEGORY_TYPE.porsche,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 2.75,
    description: "desc",
  },
  {
    src: img2,
    purchaseLink: "",
    id: 2,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.white,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 5.5,
    description: "desc",
  },
  {
    src: img3,
    purchaseLink: "",
    id: 3,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 8.25,
    description: "desc",
  },
  {
    src: img4,
    purchaseLink: "",
    id: 4,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 11,
    description: "desc",
  },
  {
    src: img5,
    purchaseLink: "",
    id: 5,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 13.75,
    description: "desc",
  },
  {
    src: img6,
    purchaseLink: "",
    id: 6,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 16.5,
    description: "desc",
  },
  {
    src: img7,
    purchaseLink: "",
    id: 7,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 19.25,
    description: "desc",
  },
  {
    src: img8,
    purchaseLink: "",
    id: 8,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 22,
    description: "desc",
  },
  {
    src: img9,
    purchaseLink: "",
    id: 9,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 24.75,
    description: "desc",
  },
  {
    src: img10,
    purchaseLink: "",
    id: 10,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 27.5,
    description: "desc",
  },
  {
    src: img11,
    purchaseLink: "",
    id: 11,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 30.25,
    description: "desc",
  },
  {
    src: img12,
    purchaseLink: "",
    id: 12,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 33,
    description: "desc",
  },
  {
    src: img13,
    purchaseLink: "",
    id: 13,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 35.75,
    description: "desc",
  },
  {
    src: img14,
    purchaseLink: "",
    id: 14,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 38.5,
    description: "desc",
  },
  {
    src: img15,
    purchaseLink: "",
    id: 15,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 41.25,
    description: "desc",
  },
  {
    src: img16,
    purchaseLink: "",
    id: 16,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 44,
    description: "desc",
  },
  {
    src: img17,
    purchaseLink: "",
    id: 17,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 46.75,
    description: "desc",
  },
  {
    src: img18,
    purchaseLink: "",
    id: 18,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 49.5,
    description: "desc",
  },
  {
    src: img19,
    purchaseLink: "",
    id: 19,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 52.25,
    description: "desc",
  },
  {
    src: img20,
    purchaseLink: "",
    id: 20,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 55,
    description: "desc",
  },
  {
    src: img21,
    purchaseLink: "",
    id: 21,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 57.75,
    description: "desc",
  },
  {
    src: img22,
    purchaseLink: "",
    id: 22,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 60.5,
    description: "desc",
  },
  {
    src: img23,
    purchaseLink: "",
    id: 23,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 63.25,
    description: "desc",
  },
  {
    src: img24,
    purchaseLink: "",
    id: 24,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 66,
    description: "desc",
  },
  {
    src: img25,
    purchaseLink: "",
    id: 25,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 68.75,
    description: "desc",
  },
  {
    src: img26,
    purchaseLink: "",
    id: 26,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 71.5,
    description: "desc",
  },
  {
    src: img27,
    purchaseLink: "",
    id: 27,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 74.25,
    description: "desc",
  },
  {
    src: img28,
    purchaseLink: "",
    id: 28,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 77,
    description: "desc",
  },
  {
    src: img29,
    purchaseLink: "",
    id: 29,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 79.75,
    description: "desc",
  },
  {
    src: img30,
    purchaseLink: "https://berlinphoto.lemonsqueezy.com/buy/3f7bdf67-c30d-452b-b0cd-25686a31a449",
    id: 30,
    category: CATEGORY_TYPE.porsche,
    name: "Porsche 944 Rear Taillight - Gritty Red Style",
    project: PROJECT_NAME.red,
    dimension: [
      DIMENSION_TYPE["2*3"],
      DIMENSION_TYPE["4*5"],
      DIMENSION_TYPE["1*1"],
      DIMENSION_TYPE["5*7"],
    ],
    price: 82.5,
    description:
      "The iconic rear quarter and taillight of a classic red Porsche 944 set against a gritty brick wall. Shot in high-contrast light with a film-like texture.",
  },
  {
    src: img31,
    purchaseLink: "",
    id: 31,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 85.25,
    description: "desc",
  },
  {
    src: img32,
    purchaseLink: "",
    id: 32,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 88,
    description: "desc",
  },
  {
    src: img33,
    purchaseLink: "",
    id: 33,
    category: CATEGORY_TYPE.ferrari,
    name: "ferrari1",
    project: PROJECT_NAME.red,
    dimension: [DIMENSION_TYPE["7*5"]],
    price: 90.75,
    description: "desc",
  },
];
